retrieve_news_task:
  description: >
    Conduct a thorough research about {topic}
    Make sure you find any interesting and relevant information given
    the current year is 2025.
  expected_output: >
    A list of top 10 websites with the most relevant information about {topic}
  agent: retrieve_news

website_scrape_task:
  description: >
    Scrape the website for the latest news and information
  expected_output: >
    A fully scraped website with all the important information from the website.
    Formatted as markdown without '```'
  agent: website_scraper

ai_news_write_task:
  description: >
    Summarize the information from websites into an informative news article
  expected_output: >
    A fully fledged news article with the main topics, each with a full section of information.
    Formatted as markdown without '```'
  agent: ai_news_writer

file_write_task:
  description: >
    Write the news article to a new file
  expected_output: >
    A fully fledged news article with all the information from the previous task into a file named news/{date}_news-article.md
    Formatted as markdown without '```'
  agent: file_writer
